export const PROJECTS = [
  {
    id: "allesguthfinance",
    name: "Alles Guth Finance",
    tagline: {
      en: "Financial clarity for budgets, imports, recurring charges, and health scores",
      pt: "Clareza financeira para orçamentos, importações, recorrências e score de saúde",
    },
    description: {
      en: "A financial management app that turns bank statements into usable decisions. Imports CSV, OFX, and PDF files, categorizes spending, detects recurring subscriptions, tracks budgets, and summarizes financial health in one score.",
      pt: "Um app de gestão financeira que transforma extratos bancários em decisões úteis. Importa CSV, OFX e PDF, categoriza gastos, detecta assinaturas recorrentes, acompanha orçamentos e resume a saúde financeira em um score.",
    },
    tags: {
      en: ["Financial SaaS", "Live product", "Full-stack"],
      pt: ["SaaS financeiro", "Produto no ar", "Full-stack"],
    },
    stack: ["React", "TypeScript", "Next.js", "Node.js", "PostgreSQL"],
    url: "https://www.allesguthfinance.com",
    code: null,
    palette: "finance",
    slides: [
      { kind: "img", src: "/assets/allesguthfinance/1.png", label: { en: "Dashboard overview", pt: "Visão geral do dashboard" } },
      { kind: "img", src: "/assets/allesguthfinance/2.png", label: { en: "Import and categorization", pt: "Importação e categorização" } },
      { kind: "img", src: "/assets/allesguthfinance/3.png", label: { en: "Budgets and goals", pt: "Orçamentos e metas" } },
      { kind: "img", src: "/assets/allesguthfinance/4.png", label: { en: "Health score", pt: "Score de saúde" } },
    ],
  },
  {
    id: "denise",
    name: "Denise Costura Criativa",
    tagline: {
      en: "Catalog and e-commerce for a Brazilian creative sewing studio",
      pt: "Catálogo e e-commerce para um ateliê brasileiro de costura criativa",
    },
    description: {
      en: "A product catalog and ordering experience for Denise Costura Criativa. Customers browse collections, inspect product details, and place orders smoothly across devices.",
      pt: "Um catálogo de produtos e experiência de pedidos para a Denise Costura Criativa. Clientes navegam por coleções, conferem detalhes dos produtos e fazem pedidos com fluidez em qualquer dispositivo.",
    },
    tags: {
      en: ["E-commerce", "Live", "Admin panel"],
      pt: ["E-commerce", "No ar", "Painel admin"],
    },
    stack: ["Next.js", "TypeScript", "React", "PostgreSQL", "CSS"],
    url: "https://www.denisecosturacriativa.com.br",
    code: null,
    palette: "atelier",
    slides: [
      { kind: "img", src: "/assets/denisecosturacriativa/home.webp", label: { en: "Home page", pt: "Página inicial" } },
      { kind: "img", src: "/assets/denisecosturacriativa/catalogo.webp", label: { en: "Product catalog", pt: "Catálogo de produtos" } },
      { kind: "img", src: "/assets/denisecosturacriativa/paginadeproduto.webp", label: { en: "Product detail", pt: "Detalhe do produto" } },
      { kind: "img", src: "/assets/denisecosturacriativa/painelAdmin.webp", label: { en: "Admin dashboard", pt: "Painel administrativo" } },
    ],
  },
  {
    id: "ngconstrua",
    name: "NGconstrua",
    tagline: {
      en: "Conversion landing page for high-end real-estate renovations",
      pt: "Landing page de conversão para reformas imobiliárias de alto padrão",
    },
    description: {
      en: "A trust-focused landing page for a renovation business. The page organizes services, project evidence, testimonials, and lead capture into one clear path.",
      pt: "Uma landing page focada em confiança para uma empresa de reformas. A página organiza serviços, prova de projetos, depoimentos e captação de leads em um caminho claro.",
    },
    tags: {
      en: ["Landing page", "Conversion", "Lead capture"],
      pt: ["Landing page", "Conversão", "Captação"],
    },
    stack: ["Next.js", "TypeScript", "React", "CSS"],
    url: "https://www.ngconstrua.com.br",
    code: null,
    palette: "build",
    slides: [
      { kind: "img", src: "/assets/ngconstrua/hero.webp", label: { en: "Hero section", pt: "Seção principal" } },
      { kind: "img", src: "/assets/ngconstrua/servicos.webp", label: { en: "Services", pt: "Serviços" } },
      { kind: "img", src: "/assets/ngconstrua/slidablePortifolio.webp", label: { en: "Project portfolio", pt: "Portfólio de projetos" } },
      { kind: "img", src: "/assets/ngconstrua/contactFooter.webp", label: { en: "Contact section", pt: "Seção de contato" } },
    ],
  },
];

export const I18N = {
  pt: {
    navOverview: "Início",
    navPortfolio: "Trabalho",
    navAbout: "Sobre",
    navContact: "Contato",
    primaryNav: "Navegação principal",
    languageLabel: "Idioma",

    eyebrowHero: "Desenvolvedor full-stack disponível",
    heroTitle: "Engenharia clara para produtos web bem acabados.",
    heroLead:
      "Sou <b>Pedro Guth</b>, dev full-stack no Brasil. Projeto, construo e coloco no ar aplicações web com:",
    ctaPortfolio: "Ver trabalhos",
    ctaContact: "Começar conversa",
    proofLabel: "Resumo profissional",
    statProjectsK: "3",
    statProjects: "projetos selecionados",
    statFull: "front e back-end",
    statLocation: "Brasil, remoto",
    statFullK: "Full-stack",
    statLocK: "BR",
    statCoffeeK: "1.240",
    statCoffee: "cafés consumidos",
    heroBoardLabel: "Retrato e projeto em destaque",
    portraitCaption: "Produto, código e entrega",
    featuredWork: "Destaque",
    stackLabel: "Stack principal",

    eyebrowPortfolio: "Trabalho entregue",
    portfolioTitle: "Projetos reais, com produto no centro.",
    portfolioSub:
      "Uma seleção curta de interfaces, sistemas e experiências que saíram do código para uso real.",
    tabProjects: "Projetos",
    tabLanguages: "Stack",
    portfolioViewLabel: "Alternar visualização do portfólio",
    slideLabel: "Slide",
    prevSlide: "Slide anterior",
    nextSlide: "Próximo slide",
    visitSite: "Visitar site",
    caseStudy: "Case sob consulta",

    eyebrowAbout: "Sobre",
    aboutTitle: "Construtor de produto, não só de telas.",
    aboutSub:
      "Gosto de transformar ideias ainda soltas em sistemas rápidos, claros e fáceis de manter.",
    aboutP1:
      "Trabalho de ponta a ponta: entendo o problema, desenho o fluxo, estruturo a base técnica e lapido a interface até ela parecer pronta para gente real.",
    aboutP2:
      "Meu dia a dia fica no ecossistema <b>TypeScript + React + Next.js</b> no front-end, com <b>Node.js + PostgreSQL</b> no back. Tenho carinho especial por performance, acessibilidade, tipografia e microinterações.",
    aboutP3:
      "Também estudo design systems, testes com Vitest, infraestrutura e maneiras melhores de transformar requisitos confusos em entregas mensuráveis.",
    factBasedL: "Localidade",
    factBasedV: "Brasil · remoto",
    factFocusL: "Foco",
    factFocusV: "Engenharia de produto",
    factStackL: "Stack",
    factStatusL: "Status",
    factStatusV: "Aberto a oportunidades",

    eyebrowContact: "Contato",
    contactTitle: "Vamos tirar uma ideia do papel.",
    contactSub:
      "Projetos, vagas, contratos ou colaboração: escolha um canal direto ou envie uma mensagem com contexto.",
    directTitle: "Canais diretos",
    directSub: "Normalmente respondo em até 24h.",
    lEmail: "Email",
    lPhone: "Telefone / WhatsApp",
    lLinkedIn: "LinkedIn",
    lGithub: "GitHub",
    copyBtn: "Copiar",
    copiedBtn: "Copiado",
    formTitle: "Enviar mensagem",
    formSub: "Um pouco de contexto ajuda a conversa começar melhor.",
    fName: "Nome",
    fEmail: "Email",
    fPhone: "Telefone",
    fTopic: "Assunto",
    fMsg: "Mensagem",
    phName: "Seu nome",
    phEmail: "voce@empresa.com",
    phPhone: "+55 ...",
    phMsg: "Objetivo, prazo, orçamento, stack atual ou qualquer detalhe útil.",
    optProject: "Discutir projeto",
    optJob: "Vaga / oportunidade",
    optFreelance: "Freelance / contrato",
    optCollab: "Colaboração",
    optOther: "Outro assunto",
    sendBtn: "Enviar mensagem",
    sendingBtn: "Enviando...",
    sentMsg: "Mensagem enviada. Retorno em breve, obrigado pelo contato.",
    errorMsg: "Não consegui enviar. Tente novamente ou use um canal direto.",

    footer: "Projetado e construído com cuidado.",
    skipToContent: "Pular para o conteúdo",
  },
  en: {
    navOverview: "Home",
    navPortfolio: "Work",
    navAbout: "About",
    navContact: "Contact",
    primaryNav: "Primary navigation",
    languageLabel: "Language",

    eyebrowHero: "Available full-stack developer",
    heroTitle: "Clear engineering for carefully finished web products.",
    heroLead:
      "I'm <b>Pedro Guth</b>, a full-stack developer in Brazil. I design, build, and ship web applications with:",
    ctaPortfolio: "View work",
    ctaContact: "Start a conversation",
    proofLabel: "Professional summary",
    statProjectsK: "3",
    statProjects: "selected projects",
    statFull: "front and back-end",
    statLocation: "Brazil, remote",
    statFullK: "Full-stack",
    statLocK: "BR",
    statCoffeeK: "1,240",
    statCoffee: "coffees consumed",
    heroBoardLabel: "Portrait and featured project",
    portraitCaption: "Product, code, delivery",
    featuredWork: "Featured",
    stackLabel: "Core stack",

    eyebrowPortfolio: "Shipped work",
    portfolioTitle: "Real projects, with product at the center.",
    portfolioSub:
      "A short selection of interfaces, systems, and experiences that moved from code into real use.",
    tabProjects: "Projects",
    tabLanguages: "Stack",
    portfolioViewLabel: "Switch portfolio view",
    slideLabel: "Slide",
    prevSlide: "Previous slide",
    nextSlide: "Next slide",
    visitSite: "Visit site",
    caseStudy: "Case on request",

    eyebrowAbout: "About",
    aboutTitle: "A product builder, not just a screen maker.",
    aboutSub:
      "I like turning loose ideas into fast, clear systems that are pleasant to maintain.",
    aboutP1:
      "I work end to end: understand the problem, shape the flow, structure the technical base, and polish the interface until it feels ready for real people.",
    aboutP2:
      "My daily stack sits around <b>TypeScript + React + Next.js</b> on the front-end, with <b>Node.js + PostgreSQL</b> on the back. I care about performance, accessibility, typography, and small interactions.",
    aboutP3:
      "I also study design systems, Vitest testing, infrastructure, and better ways to turn messy requirements into measurable delivery.",
    factBasedL: "Based in",
    factBasedV: "Brazil · remote",
    factFocusL: "Focus",
    factFocusV: "Product engineering",
    factStackL: "Stack",
    factStatusL: "Status",
    factStatusV: "Open to opportunities",

    eyebrowContact: "Contact",
    contactTitle: "Let's move an idea into production.",
    contactSub:
      "Projects, roles, contracts, or collaboration: choose a direct channel or send a note with context.",
    directTitle: "Direct channels",
    directSub: "Usually replies within 24h.",
    lEmail: "Email",
    lPhone: "Phone / WhatsApp",
    lLinkedIn: "LinkedIn",
    lGithub: "GitHub",
    copyBtn: "Copy",
    copiedBtn: "Copied",
    formTitle: "Send a message",
    formSub: "A bit of context helps the conversation start well.",
    fName: "Name",
    fEmail: "Email",
    fPhone: "Phone",
    fTopic: "Topic",
    fMsg: "Message",
    phName: "Your name",
    phEmail: "you@company.com",
    phPhone: "+55 ...",
    phMsg: "Goal, timeline, budget, current stack, or any useful detail.",
    optProject: "Discuss a project",
    optJob: "Job / role opportunity",
    optFreelance: "Freelance / contract",
    optCollab: "Collaboration",
    optOther: "Something else",
    sendBtn: "Send message",
    sendingBtn: "Sending...",
    sentMsg: "Message sent. I'll get back to you soon, thanks for reaching out.",
    errorMsg: "I could not send that. Please try again or use a direct channel.",

    footer: "Designed and built with care.",
    skipToContent: "Skip to content",
  },
};

export const LANGUAGES = [
  { short: "TS", full: "TypeScript", level: "Primary language" },
  { short: "React", full: "React", level: "Interfaces" },
  { short: "Next", full: "Next.js", level: "Apps and sites" },
  { short: "Node", full: "Node.js", level: "APIs" },
  { short: "PgSQL", full: "PostgreSQL", level: "Data" },
  { short: "CSS", full: "Modern CSS", level: "UI systems" },
  { short: "HTML", full: "Semantic HTML", level: "Accessibility" },
  { short: "Vitest", full: "Vitest", level: "Testing" },
];

export const STATS = [
  { key: "statProjects", val: "3", label: "statProjects" },
  { key: "statFull", val: "Full-stack", label: "statFull" },
  { key: "statLoc", val: "BR", label: "statLocation" },
  { key: "statCoffee", val: "1.240", label: "statCoffee" },
];

export const NAV_SECTIONS = [
  { id: "overview", label: "Home" },
  { id: "portfolio", label: "Work" },
  { id: "about", label: "About" },
  { id: "contact", label: "Contact" },
];
